<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Listado de empleados</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="panel panel-green">
        <div class="panel-heading">
            Lista de empleados
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <th>Código</th>
                    <th>Estado</th>
                </tr>
                <?php foreach ($this->employees as $employee) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($employee->getCompanyCode()); ?></td>
                        <td><?php echo $this->escapeHtml($employee->getStatus()); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <!-- /.row -->
</div>