<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Sipp</h1>
            <p>Sistema de información para Pymes</p>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="panel panel-green">
        <div class="panel-heading">
            Empresas
        </div>
        <div class="panel-body">
            <a href="/sipp/company">Ver empresas</a>
        </div>
    </div>
    <div class="panel panel-green">
        <div class="panel-heading">
            Empleados
        </div>
        <div class="panel-body">
            <a href="/sipp/employee">Ver empleados</a>
        </div>
    </div>
</div>