<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Sipp</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <a href="/sipp/company">Ver empresas</a>
                    </div>
                    <div class="row">
                        <a href="/sipp/employee">Ver empleados</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
</div>