<div class="row">
    Borrar empresa
</div>
<?php if (isset($this->message)): ?>
<div class="row">
    <?php echo $this->message; ?>
</div>
<?php endif; ?>
<?php
    $title = 'Borrar empresa';
    $this->headTitle($title);
?>
<div class="row">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <p>¿Está seguro de borrar la empresa
         '<?php echo $this->escapeHtml($this->employee->getName()); ?>' de
         '<?php echo $this->escapeHtml($this->employee->getState()); ?>'?
    </p>
    <?php
        $url = $this->url('sipp/crud_entities', array(
             'controller' => 'company',
             'action' => 'delete',
             'id'     => $this->id,
    ));
    ?>
    <form action="<?php echo $url; ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->company->getId(); ?>" />
            <input type="submit" name="del" value="Yes" />
            <input type="submit" name="del" value="No" />
        </div>
    </form>
 </div>