<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Listado de empresas</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="panel panel-green">
        <div class="panel-heading">
            Lista de empresas registradas
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                </tr>
                <?php foreach ($this->companies as $company) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($company->getId()); ?></td>
                        <td><?php echo $this->escapeHtml($company->getName()); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <!-- /.row -->
</div>