<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Listado de empresas</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        Lista de empresas registradas
                        <div class="col-xs-9 text-right">
                            <table class="table">
                                <tr>
                                    <th>Id</th>
                                    <th>Nombre</th>
                                    <th>&nbsp;</th>
                                </tr>
                                <?php foreach ($this->companies as $company) : ?>
                                    <tr>
                                        <td><?php echo $this->escapeHtml($company->getId()); ?></td>
                                        <td><?php echo $this->escapeHtml($company->getName()); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
</div>