Sipp\Entity\Company:
  type: entity
  table: company
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
    code:
      type: string
      length: 100
    state:
      type: integer
  oneToMany:
    employees:
      targetEntity: Employee
      mappedBy: company
      joinColumn:
        name: company_code
        referencedColumnName: code
        onDelete: CASCADE