Sipp\Entity\Employee:
  type: entity
  table: employee
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    user_id:
      type: integer
    company_code:
      type: string
      length: 100
    state:
      type: integer