Application\Entity\Album:
  type: entity
  repositoryClass: Application\Entity\AlbumRepository
  table: album
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    artist:
      type: string
      length: 100
    title:
      type: string
      length: 100
    company_id:
      type: integer
    oneToMany:
      companies:
        targetEntity: Company
        mappedBy: album