<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Eduardo Escamilla')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php 
            // Etiquetas Meta
            echo $this->headMeta()
                    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
            // Estilos generales
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))  
                    ->prependStylesheet($this->basePath('css/style.css'))    
                    ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
                    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                    ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css')) 
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        &nbsp;Eduardo Escamilla
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="<?php echo $this->url('home') ?>">
                                <?php echo $this->translate('Home') ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('sipp') ?>">
                                <?php echo $this->translate('Sipp') ?>
                            </a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> por Eduardo Escamilla</p>
            </footer>
        </div> <!-- /container -->
        <!-- Scripts -->
        <?php 
            echo $this->inlineScript()
                    ->prependFile($this->basePath('bower_components/bootstrap/dist/js/bootstrap.min.js'))
                    ->prependFile($this->basePath('bower_components/jquery/dist/jquery.min.js'));
        ?>
    </body>
</html>