<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sipp\Module'                        => __DIR__ . '/Module.php',
    'Sipp\Controller\IndexController' => __DIR__ . '/src/Sipp/Controller/IndexController.php',
    'SippTest\Framework\TestCase'        => __DIR__ . '/tests/Sipp/Framework/TestCase.php',
    'SippTest\SampleTest'                => __DIR__ . '/tests/Sipp/SampleTest.php',
);