<div class="jumbotron">
    <h1>
        <span class="zf-green">Eduardo Escamilla</span>
    </h1>
    <p>
        Página de pruebas y ensayos en pro de un desarrollo mejor.
    </p>
</div>

<div class="row">
    Prueba 1:
    Usando Doctrine :)
    Con Tutorial de ZF2
    <?php
    $form->setAttribute('action', '/add');
    $form->prepare();
    echo $this->form()->openTag($form);
    /*
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('title'));
    echo $this->formRow($form->get('artist'));
    echo $this->formSubmit($form->get('submit'));
    */
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>