<div class="jumbotron">
    <h1>
        <span class="zf-green">Eduardo Escamilla</span>
    </h1>
    <p>
        Página de pruebas y ensayos en pro de un desarrollo mejor.
    </p>
</div>

<div class="row">
    Prueba 1:
    Usando Doctrine :)
    Con Tutorial de ZF2
    <table class="table">
        <tr>
            <th>Title</th>
            <th>Artist</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($this->albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title);?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>