<h1>Ingresar</h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>

<?php echo $this->partial('_form.phtml', ['form' => $form]); ?>

<?php if ($this->enableRegistration) : ?>
¿No estás registrado?
<a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>">
    ¡Regístrate!
</a>
<?php endif; ?>